# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv load_addr "0x39000000"
setenv overlay_error "false"

# default values (used only if not defined in armbianEnv.txt)
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv rootflags "rw,errors=remount-ro"
setenv docker_optimizations "on"
setenv earlycon "off"
setenv consoleargs ""
setenv earlyconargs ""
setenv usbstoragequirks ""
setenv extraargs ""
setenv extraboardargs ""

echo "Boot script loaded from ${devtype} ${devnum}"

# Load and import armbianEnv.txt (overrides default values)
if test -e ${devtype} ${devnum} ${prefix}armbianEnv.txt; then
	load ${devtype} ${devnum} ${load_addr} ${prefix}armbianEnv.txt
	env import -t ${load_addr} ${filesize}
fi

# --- 修正点：控制台参数处理 ---
# 如果 armbianEnv.txt 中定义了 consoleargs，直接使用它
if test -n "${consoleargs}"; then
	# 用户已自定义完整的 consoleargs（如 "console=ttyFIQ0,1500000"）
	setenv final_consoleargs "${consoleargs}"
else
	# 否则根据 console 变量构造（兼容旧方式）
	setenv final_consoleargs ""
	if test "${console}" = "display" || test "${console}" = "both"; then
		setenv final_consoleargs "console=tty1"
	fi
	if test "${console}" = "serial" || test "${console}" = "both"; then
		# 默认串口设备，请根据你的平台修改（ttyFIQ0 或 ttyS2 等）
		setenv final_consoleargs "${final_consoleargs} console=ttyFIQ0,1500000"
	fi
fi

# 处理 earlycon（如果启用且定义了 earlyconargs）
if test "${earlycon}" = "on" && test -n "${earlyconargs}"; then
	setenv final_consoleargs "${earlyconargs} ${final_consoleargs}"
fi

# 处理 bootlogo
if test "${bootlogo}" = "true"; then
	setenv final_consoleargs "bootsplash.bootfile=bootsplash.armbian ${final_consoleargs}"
fi
# --- 控制台参数处理结束 ---

# 获取第一个分区的 PARTUUID（备用，但当前我们直接用 rootdev）
if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:1 partuuid; fi

# 构造最终的 bootargs
setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} rootflags=${rootflags} ${final_consoleargs} consoleblank=0 loglevel=${verbosity} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

# Docker 优化参数
if test "${docker_optimizations}" = "on"; then
	setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"
fi

# 加载 initrd、kernel 和 dtb
load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image
load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}

# 应用设备树覆盖（overlays）
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done

# 错误处理及 fixup 脚本
if test "${overlay_error}" = "true"; then
	echo "Error applying DT overlays, restoring original DT"
	load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
	if load ${devtype} ${devnum} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
		echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
		source ${load_addr}
	fi
	if test -e ${devtype} ${devnum} ${prefix}fixup.scr; then
		load ${devtype} ${devnum} ${load_addr} ${prefix}fixup.scr
		echo "Applying user provided fixup script (fixup.scr)"
		source ${load_addr}
	fi
fi

# 启动内核
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}
